# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_CSales.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CASHIER_SALES(object):
    def setupUi(self, CASHIER_SALES):
        CASHIER_SALES.setObjectName("CASHIER_SALES")
        CASHIER_SALES.resize(1921, 1005)
        CASHIER_SALES.setStyleSheet("background: white;")
        self.Owner_centralwidget = QtWidgets.QWidget(CASHIER_SALES)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Owner_centralwidget.setFont(font)
        self.Owner_centralwidget.setObjectName("Owner_centralwidget")
        self.LeftMenuBar = QtWidgets.QFrame(self.Owner_centralwidget)
        self.LeftMenuBar.setGeometry(QtCore.QRect(-1, -1, 301, 981))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LeftMenuBar.setFont(font)
        self.LeftMenuBar.setStyleSheet("background-color: rgba(235, 224, 204, 0.47); /* #ebe0cc with 47% opacity */")
        self.LeftMenuBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LeftMenuBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LeftMenuBar.setObjectName("LeftMenuBar")
        self.JJelevate_text = QtWidgets.QLabel(self.LeftMenuBar)
        self.JJelevate_text.setGeometry(QtCore.QRect(30, 250, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.JJelevate_text.setFont(font)
        self.JJelevate_text.setStyleSheet("color: #12245c; \n"
"background: transparent;\n"
"")
        self.JJelevate_text.setScaledContents(True)
        self.JJelevate_text.setObjectName("JJelevate_text")
        self.Logo = QtWidgets.QLabel(self.LeftMenuBar)
        self.Logo.setGeometry(QtCore.QRect(30, 50, 241, 171))
        self.Logo.setStyleSheet("background: transparent;")
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap(":/JJimages/JJLOGO.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setAlignment(QtCore.Qt.AlignCenter)
        self.Logo.setObjectName("Logo")
        self.pushButton_Dashboard_CASHIER = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Dashboard_CASHIER.setGeometry(QtCore.QRect(30, 310, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_Dashboard_CASHIER.setFont(font)
        self.pushButton_Dashboard_CASHIER.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"color:black;\n"
"font-weight: 700;\n"
"}\n"
"QPushButton#activeButton {\n"
"    background-color:#c25b55;\n"
"color:black;\n"
"font-weight: 700;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/JJimages/dashboard_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Dashboard_CASHIER.setIcon(icon)
        self.pushButton_Dashboard_CASHIER.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Dashboard_CASHIER.setObjectName("pushButton_Dashboard_CASHIER")
        self.pushButton_Inventory_CASHIER = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Inventory_CASHIER.setGeometry(QtCore.QRect(30, 390, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Inventory_CASHIER.setFont(font)
        self.pushButton_Inventory_CASHIER.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"color:black;\n"
"font-weight: 700;\n"
"}\n"
"QPushButton#activeButton {\n"
"    background-color:#c25b55;\n"
"color:black;\n"
"font-weight: 700;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/JJimages/inventory_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Inventory_CASHIER.setIcon(icon1)
        self.pushButton_Inventory_CASHIER.setIconSize(QtCore.QSize(50, 45))
        self.pushButton_Inventory_CASHIER.setObjectName("pushButton_Inventory_CASHIER")
        self.pushButton_Orders_CASHIER = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Orders_CASHIER.setGeometry(QtCore.QRect(30, 470, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Orders_CASHIER.setFont(font)
        self.pushButton_Orders_CASHIER.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"color:black;\n"
"font-weight: 700;\n"
"}\n"
"QPushButton#activeButton {\n"
"    background-color:#c25b55;\n"
"color:black;\n"
"font-weight: 700;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/JJimages/orders_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Orders_CASHIER.setIcon(icon2)
        self.pushButton_Orders_CASHIER.setIconSize(QtCore.QSize(46, 42))
        self.pushButton_Orders_CASHIER.setObjectName("pushButton_Orders_CASHIER")
        self.pushButton_Sales_CASHIER = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Sales_CASHIER.setGeometry(QtCore.QRect(30, 550, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Sales_CASHIER.setFont(font)
        self.pushButton_Sales_CASHIER.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"color:black;\n"
"font-weight: 700;\n"
"}\n"
"QPushButton#activeButton {\n"
"    background-color:#c25b55;\n"
"color:black;\n"
"font-weight: 700;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/JJimages/sales_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Sales_CASHIER.setIcon(icon3)
        self.pushButton_Sales_CASHIER.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_Sales_CASHIER.setObjectName("pushButton_Sales_CASHIER")
        self.pushButton_Account_CASHIER = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Account_CASHIER.setGeometry(QtCore.QRect(30, 710, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Account_CASHIER.setFont(font)
        self.pushButton_Account_CASHIER.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"color:black;\n"
"font-weight: 700;\n"
"}\n"
"QPushButton#activeButton {\n"
"    background-color:#c25b55;\n"
"color:black;\n"
"font-weight: 700;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/JJimages/account_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Account_CASHIER.setIcon(icon4)
        self.pushButton_Account_CASHIER.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_Account_CASHIER.setObjectName("pushButton_Account_CASHIER")
        self.pushButton_LogOut_CASHIER = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_LogOut_CASHIER.setGeometry(QtCore.QRect(30, 890, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(87)
        self.pushButton_LogOut_CASHIER.setFont(font)
        self.pushButton_LogOut_CASHIER.setStyleSheet("QPushButton {\n"
"    background-color:#022162;\n"
"color:white;\n"
"font-weight: 700;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"font-size: 14;\n"
"text-align: left;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/JJimages/WHITElogout_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_LogOut_CASHIER.setIcon(icon5)
        self.pushButton_LogOut_CASHIER.setIconSize(QtCore.QSize(38, 38))
        self.pushButton_LogOut_CASHIER.setObjectName("pushButton_LogOut_CASHIER")
        self.pushButton_Stock_History_CASHIER = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Stock_History_CASHIER.setGeometry(QtCore.QRect(30, 630, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Stock_History_CASHIER.setFont(font)
        self.pushButton_Stock_History_CASHIER.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"color:black;\n"
"font-weight: 700;\n"
"}\n"
"QPushButton#activeButton {\n"
"    background-color:#c25b55;\n"
"color:black;\n"
"font-weight: 700;\n"
"}\n"
"")
        self.pushButton_Stock_History_CASHIER.setIcon(icon1)
        self.pushButton_Stock_History_CASHIER.setIconSize(QtCore.QSize(50, 45))
        self.pushButton_Stock_History_CASHIER.setObjectName("pushButton_Stock_History_CASHIER")
        self.sales_inview = QtWidgets.QWidget(self.Owner_centralwidget)
        self.sales_inview.setGeometry(QtCore.QRect(300, 0, 1931, 1005))
        self.sales_inview.setObjectName("sales_inview")
        self.frame_45 = QtWidgets.QFrame(self.sales_inview)
        self.frame_45.setGeometry(QtCore.QRect(0, 0, 1621, 211))
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.comboBox_filterSales = QtWidgets.QComboBox(self.frame_45)
        self.comboBox_filterSales.setGeometry(QtCore.QRect(1350, 50, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.comboBox_filterSales.setFont(font)
        self.comboBox_filterSales.setStyleSheet("    background-color: #ebe0cc;\n"
"    border-radius: 15px;\n"
"font-size:28px;\n"
"text-align: center;")
        self.comboBox_filterSales.setObjectName("comboBox_filterSales")
        self.comboBox_filterSales.addItem("")
        self.comboBox_filterSales.addItem("")
        self.comboBox_filterSales.addItem("")
        self.comboBox_filterSales.addItem("")
        self.frame_29 = QtWidgets.QFrame(self.frame_45)
        self.frame_29.setGeometry(QtCore.QRect(50, 150, 661, 61))
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.pushButton_summaryView = QtWidgets.QPushButton(self.frame_29)
        self.pushButton_summaryView.setGeometry(QtCore.QRect(0, 10, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        self.pushButton_summaryView.setFont(font)
        self.pushButton_summaryView.setStyleSheet("QPushButton {\n"
"    background-color: #003366; /* Blue color */\n"
"    border-radius: 10px;\n"
"    font-size: 24px;\n"
"    color: #ffffff; /* Corrected from font-color */\n"
"    padding: 9px;\n"
"    font-family: \"Verdana\", sans-serif;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color: #8d2721;\n"
"    color: #ffffff; /* Ensure text color remains white */\n"
"}\n"
"\n"
"/* Active Button (Current Page) */\n"
"QPushButton#activeButton {\n"
"    background-color:#8d2721;\n"
"    color: #ffffff; /* Ensure text color remains white */\n"
"}")
        self.pushButton_summaryView.setObjectName("pushButton_summaryView")
        self.pushButton_salesDetail = QtWidgets.QPushButton(self.frame_29)
        self.pushButton_salesDetail.setGeometry(QtCore.QRect(260, 10, 281, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        self.pushButton_salesDetail.setFont(font)
        self.pushButton_salesDetail.setStyleSheet("QPushButton {\n"
"    background-color: #003366; /* Blue color */\n"
"    border-radius: 10px;\n"
"    font-size: 24px;\n"
"    color: #ffffff; /* Corrected from font-color */\n"
"    padding: 9px;\n"
"    font-family: \"Verdana\", sans-serif;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color: #8d2721;\n"
"    color: #ffffff; /* Ensure text color remains white */\n"
"}\n"
"\n"
"/* Active Button (Current Page) */\n"
"QPushButton#activeButton {\n"
"    background-color: #8d2721;\n"
"    color: #ffffff; /* Ensure text color remains white */\n"
"}")
        self.pushButton_salesDetail.setObjectName("pushButton_salesDetail")
        self.salesReportText = QtWidgets.QLabel(self.frame_45)
        self.salesReportText.setGeometry(QtCore.QRect(60, 50, 501, 71))
        self.salesReportText.setStyleSheet("font-size:50px;\n"
"background: transparent;")
        self.salesReportText.setObjectName("salesReportText")
        self.stackedWidget = QtWidgets.QStackedWidget(self.sales_inview)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 210, 1621, 771))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.tableWidget_salesSummary = QtWidgets.QTableWidget(self.page)
        self.tableWidget_salesSummary.setGeometry(QtCore.QRect(50, 0, 1531, 741))
        self.tableWidget_salesSummary.setStyleSheet(" \n"
"QTableWidget {\n"
"    background-color: white;\n"
"    gridline-color: lightgray;\n"
"    selection-background-color: #ebe0cc;\n"
"    selection-color: white;               /* selected row text */\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: #b33c35;  /* slightly lighter hover effect */\n"
"    color: white;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #c25b55; /* deep maroon header */\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 4px;\n"
"    border: 1px solid lightgray;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding-left: 12px;\n"
"    padding-right: 12px;\n"
"}")
        self.tableWidget_salesSummary.setObjectName("tableWidget_salesSummary")
        self.tableWidget_salesSummary.setColumnCount(6)
        self.tableWidget_salesSummary.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_salesSummary.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_salesSummary.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_salesSummary.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_salesSummary.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_salesSummary.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_salesSummary.setHorizontalHeaderItem(5, item)
        self.tableWidget_salesSummary.horizontalHeader().setDefaultSectionSize(265)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tableWidget_salesDetails = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget_salesDetails.setGeometry(QtCore.QRect(50, 0, 1531, 741))
        self.tableWidget_salesDetails.setStyleSheet("\n"
"QTableWidget {\n"
"    background-color: white;\n"
"    gridline-color: lightgray;\n"
"    selection-background-color: #ebe0cc;\n"
"    selection-color: white;               /* selected row text */\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: #b33c35;  /* slightly lighter hover effect */\n"
"    color: white;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #c25b55; /* deep maroon header */\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 4px;\n"
"    border: 1px solid lightgray;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding-left: 12px;\n"
"    padding-right: 12px;\n"
"}\n"
"\n"
"")
        self.tableWidget_salesDetails.setObjectName("tableWidget_salesDetails")
        self.tableWidget_salesDetails.setColumnCount(5)
        self.tableWidget_salesDetails.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_salesDetails.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_salesDetails.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_salesDetails.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_salesDetails.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_salesDetails.setHorizontalHeaderItem(4, item)
        self.tableWidget_salesDetails.horizontalHeader().setDefaultSectionSize(265)
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(110, 140, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page_2)
        CASHIER_SALES.setCentralWidget(self.Owner_centralwidget)
        self.statusbar = QtWidgets.QStatusBar(CASHIER_SALES)
        self.statusbar.setObjectName("statusbar")
        CASHIER_SALES.setStatusBar(self.statusbar)

        self.retranslateUi(CASHIER_SALES)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(CASHIER_SALES)

    def retranslateUi(self, CASHIER_SALES):
        _translate = QtCore.QCoreApplication.translate
        CASHIER_SALES.setWindowTitle(_translate("CASHIER_SALES", "Inventory and Sales Management System"))
        self.JJelevate_text.setText(_translate("CASHIER_SALES", "J & J ELEVATE"))
        self.pushButton_Dashboard_CASHIER.setText(_translate("CASHIER_SALES", " Dashboard   "))
        self.pushButton_Inventory_CASHIER.setText(_translate("CASHIER_SALES", "Inventory"))
        self.pushButton_Orders_CASHIER.setText(_translate("CASHIER_SALES", " Orders"))
        self.pushButton_Sales_CASHIER.setText(_translate("CASHIER_SALES", "  Sales"))
        self.pushButton_Account_CASHIER.setText(_translate("CASHIER_SALES", " Account     "))
        self.pushButton_LogOut_CASHIER.setText(_translate("CASHIER_SALES", "Log out"))
        self.pushButton_Stock_History_CASHIER.setText(_translate("CASHIER_SALES", "Stock History"))
        self.comboBox_filterSales.setCurrentText(_translate("CASHIER_SALES", "    Filter Sales"))
        self.comboBox_filterSales.setItemText(0, _translate("CASHIER_SALES", "    Filter Sales"))
        self.comboBox_filterSales.setItemText(1, _translate("CASHIER_SALES", "Daily"))
        self.comboBox_filterSales.setItemText(2, _translate("CASHIER_SALES", "Weekly"))
        self.comboBox_filterSales.setItemText(3, _translate("CASHIER_SALES", "Monthly"))
        self.pushButton_summaryView.setText(_translate("CASHIER_SALES", "Summary View"))
        self.pushButton_salesDetail.setText(_translate("CASHIER_SALES", "Detailed View"))
        self.salesReportText.setText(_translate("CASHIER_SALES", "Sales Report"))
        item = self.tableWidget_salesSummary.horizontalHeaderItem(0)
        item.setText(_translate("CASHIER_SALES", "Report ID"))
        item = self.tableWidget_salesSummary.horizontalHeaderItem(1)
        item.setText(_translate("CASHIER_SALES", "Shop Branch"))
        item = self.tableWidget_salesSummary.horizontalHeaderItem(2)
        item.setText(_translate("CASHIER_SALES", "Report Type"))
        item = self.tableWidget_salesSummary.horizontalHeaderItem(3)
        item.setText(_translate("CASHIER_SALES", "Total Quantity Sold"))
        item = self.tableWidget_salesSummary.horizontalHeaderItem(4)
        item.setText(_translate("CASHIER_SALES", "Total Revenue (₱)"))
        item = self.tableWidget_salesSummary.horizontalHeaderItem(5)
        item.setText(_translate("CASHIER_SALES", "Date Generated"))
        item = self.tableWidget_salesDetails.horizontalHeaderItem(0)
        item.setText(_translate("CASHIER_SALES", "Detail ID"))
        item = self.tableWidget_salesDetails.horizontalHeaderItem(1)
        item.setText(_translate("CASHIER_SALES", "Product Name"))
        item = self.tableWidget_salesDetails.horizontalHeaderItem(2)
        item.setText(_translate("CASHIER_SALES", "Quantity Sold"))
        item = self.tableWidget_salesDetails.horizontalHeaderItem(3)
        item.setText(_translate("CASHIER_SALES", "Total Sales Amount (₱)"))
        item = self.tableWidget_salesDetails.horizontalHeaderItem(4)
        item.setText(_translate("CASHIER_SALES", "Date Recorded"))
        self.label.setText(_translate("CASHIER_SALES", "CASHIER"))
from ui.resources import jj_resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CASHIER_SALES = QtWidgets.QMainWindow()
    ui = Ui_CASHIER_SALES()
    ui.setupUi(CASHIER_SALES)
    CASHIER_SALES.show()
    sys.exit(app.exec_())
