# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/raw_files/UI_COrders.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CASHIER_ORDERS(object):
    def setupUi(self, CASHIER_ORDERS):
        CASHIER_ORDERS.setObjectName("CASHIER_ORDERS")
        CASHIER_ORDERS.resize(1921, 1005)
        self.LeftMenuBar = QtWidgets.QFrame(CASHIER_ORDERS)
        self.LeftMenuBar.setGeometry(QtCore.QRect(-1, -1, 301, 981))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LeftMenuBar.setFont(font)
        self.LeftMenuBar.setStyleSheet("background-color: rgba(235, 224, 204, 0.47); /* #ebe0cc with 47% opacity */")
        self.LeftMenuBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LeftMenuBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LeftMenuBar.setObjectName("LeftMenuBar")
        self.JJelevate_text = QtWidgets.QLabel(self.LeftMenuBar)
        self.JJelevate_text.setGeometry(QtCore.QRect(30, 250, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.JJelevate_text.setFont(font)
        self.JJelevate_text.setStyleSheet("color: #12245c; \n"
"background: transparent;\n"
"")
        self.JJelevate_text.setScaledContents(True)
        self.JJelevate_text.setObjectName("JJelevate_text")
        self.Logo = QtWidgets.QLabel(self.LeftMenuBar)
        self.Logo.setGeometry(QtCore.QRect(30, 50, 241, 171))
        self.Logo.setStyleSheet("background: transparent;")
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("ui/raw_files\\../../../../Documents/assets/images/JJLOGO.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setAlignment(QtCore.Qt.AlignCenter)
        self.Logo.setObjectName("Logo")
        self.pushButton_Dashboard_CASHIER = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Dashboard_CASHIER.setGeometry(QtCore.QRect(30, 310, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_Dashboard_CASHIER.setFont(font)
        self.pushButton_Dashboard_CASHIER.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"color:black;\n"
"font-weight: 700;\n"
"}\n"
"QPushButton#activeButton {\n"
"    background-color:#c25b55;\n"
"color:black;\n"
"font-weight: 700;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/raw_files\\../../../../Documents/assets/images/dashboard_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Dashboard_CASHIER.setIcon(icon)
        self.pushButton_Dashboard_CASHIER.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Dashboard_CASHIER.setObjectName("pushButton_Dashboard_CASHIER")
        self.pushButton_Inventory_CASHIER = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Inventory_CASHIER.setGeometry(QtCore.QRect(30, 390, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Inventory_CASHIER.setFont(font)
        self.pushButton_Inventory_CASHIER.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"color:black;\n"
"font-weight: 700;\n"
"}\n"
"QPushButton#activeButton {\n"
"    background-color:#c25b55;\n"
"color:black;\n"
"font-weight: 700;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui/raw_files\\../../../../Documents/assets/images/inventory_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Inventory_CASHIER.setIcon(icon1)
        self.pushButton_Inventory_CASHIER.setIconSize(QtCore.QSize(50, 45))
        self.pushButton_Inventory_CASHIER.setObjectName("pushButton_Inventory_CASHIER")
        self.pushButton_Orders_CASHIER = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Orders_CASHIER.setGeometry(QtCore.QRect(30, 470, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Orders_CASHIER.setFont(font)
        self.pushButton_Orders_CASHIER.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"color:black;\n"
"font-weight: 700;\n"
"}\n"
"QPushButton#activeButton {\n"
"    background-color:#c25b55;\n"
"color:black;\n"
"font-weight: 700;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui/raw_files\\../../../../Documents/assets/images/orders_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Orders_CASHIER.setIcon(icon2)
        self.pushButton_Orders_CASHIER.setIconSize(QtCore.QSize(46, 42))
        self.pushButton_Orders_CASHIER.setObjectName("pushButton_Orders_CASHIER")
        self.pushButton_Sales_CASHIER = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Sales_CASHIER.setGeometry(QtCore.QRect(30, 550, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Sales_CASHIER.setFont(font)
        self.pushButton_Sales_CASHIER.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"color:black;\n"
"font-weight: 700;\n"
"}\n"
"QPushButton#activeButton {\n"
"    background-color:#c25b55;\n"
"color:black;\n"
"font-weight: 700;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ui/raw_files\\../../../../Documents/assets/images/sales_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Sales_CASHIER.setIcon(icon3)
        self.pushButton_Sales_CASHIER.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_Sales_CASHIER.setObjectName("pushButton_Sales_CASHIER")
        self.pushButton_Account_CASHIER = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Account_CASHIER.setGeometry(QtCore.QRect(30, 710, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Account_CASHIER.setFont(font)
        self.pushButton_Account_CASHIER.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"color:black;\n"
"font-weight: 700;\n"
"}\n"
"QPushButton#activeButton {\n"
"    background-color:#c25b55;\n"
"color:black;\n"
"font-weight: 700;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ui/raw_files\\../../../../Documents/assets/images/account_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Account_CASHIER.setIcon(icon4)
        self.pushButton_Account_CASHIER.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_Account_CASHIER.setObjectName("pushButton_Account_CASHIER")
        self.pushButton_LogOut_CASHIER = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_LogOut_CASHIER.setGeometry(QtCore.QRect(30, 890, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(87)
        self.pushButton_LogOut_CASHIER.setFont(font)
        self.pushButton_LogOut_CASHIER.setStyleSheet("QPushButton {\n"
"    background-color:#022162;\n"
"color:white;\n"
"font-weight: 700;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"font-size: 14;\n"
"text-align: left;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ui/raw_files\\../../../../Documents/assets/images/WHITElogout_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_LogOut_CASHIER.setIcon(icon5)
        self.pushButton_LogOut_CASHIER.setIconSize(QtCore.QSize(38, 38))
        self.pushButton_LogOut_CASHIER.setObjectName("pushButton_LogOut_CASHIER")
        self.pushButton_Stock_History_CASHIER = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Stock_History_CASHIER.setGeometry(QtCore.QRect(30, 630, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Stock_History_CASHIER.setFont(font)
        self.pushButton_Stock_History_CASHIER.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"color:black;\n"
"font-weight: 700;\n"
"}\n"
"QPushButton#activeButton {\n"
"    background-color:#c25b55;\n"
"color:black;\n"
"font-weight: 700;\n"
"}\n"
"")
        self.pushButton_Stock_History_CASHIER.setIcon(icon1)
        self.pushButton_Stock_History_CASHIER.setIconSize(QtCore.QSize(50, 45))
        self.pushButton_Stock_History_CASHIER.setObjectName("pushButton_Stock_History_CASHIER")
        self.stackedWidget = QtWidgets.QStackedWidget(CASHIER_ORDERS)
        self.stackedWidget.setGeometry(QtCore.QRect(300, 210, 1621, 771))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.tableWidget_order = QtWidgets.QTableWidget(self.page)
        self.tableWidget_order.setGeometry(QtCore.QRect(50, 0, 1531, 741))
        self.tableWidget_order.setStyleSheet("padding: 1;")
        self.tableWidget_order.setObjectName("tableWidget_order")
        self.tableWidget_order.setColumnCount(9)
        self.tableWidget_order.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_order.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_order.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_order.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_order.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_order.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_order.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_order.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_order.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_order.setHorizontalHeaderItem(8, item)
        self.tableWidget_order.horizontalHeader().setDefaultSectionSize(265)
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(90, 100, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tableWidget_orderDetails = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget_orderDetails.setGeometry(QtCore.QRect(50, 0, 1531, 741))
        self.tableWidget_orderDetails.setStyleSheet("padding: 1;")
        self.tableWidget_orderDetails.setObjectName("tableWidget_orderDetails")
        self.tableWidget_orderDetails.setColumnCount(8)
        self.tableWidget_orderDetails.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_orderDetails.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_orderDetails.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_orderDetails.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_orderDetails.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_orderDetails.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_orderDetails.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_orderDetails.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_orderDetails.setHorizontalHeaderItem(7, item)
        self.tableWidget_orderDetails.horizontalHeader().setDefaultSectionSize(265)
        self.stackedWidget.addWidget(self.page_2)
        self.frame_45 = QtWidgets.QFrame(CASHIER_ORDERS)
        self.frame_45.setGeometry(QtCore.QRect(300, 0, 1621, 211))
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.lineEdit__QuickSearch_Sales = QtWidgets.QLineEdit(self.frame_45)
        self.lineEdit__QuickSearch_Sales.setGeometry(QtCore.QRect(50, 50, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.lineEdit__QuickSearch_Sales.setFont(font)
        self.lineEdit__QuickSearch_Sales.setStyleSheet("lineEdit__QuickSearch_Sales {\n"
"    background-color: #003366;\n"
"    border-radius: 10px; /* Test with a smaller value */\n"
"    border: 1px solid #ffffff; /* Add a border for visibility */\n"
"    padding: 3px;\n"
"    color: #ffffff;\n"
"    font-size: 20px;\n"
"    font-family: \"Verdana\", sans-serif; \n"
"    text-align: center;\n"
"}")
        self.lineEdit__QuickSearch_Sales.setInputMask("")
        self.lineEdit__QuickSearch_Sales.setText("")
        self.lineEdit__QuickSearch_Sales.setClearButtonEnabled(False)
        self.lineEdit__QuickSearch_Sales.setObjectName("lineEdit__QuickSearch_Sales")
        self.pushButton_search = QtWidgets.QPushButton(self.frame_45)
        self.pushButton_search.setGeometry(QtCore.QRect(330, 50, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        self.pushButton_search.setFont(font)
        self.pushButton_search.setStyleSheet("QPushButton {\n"
"    background-color: #003366; /* Blue color */\n"
"    border-radius: 20px;\n"
"    font-size: 28px;\n"
"    color: #ffffff; /* Corrected from font-color */\n"
"    padding: 9px;\n"
"    font-family: \"Verdana\", sans-serif;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color: #004aad;\n"
"    color: #ffffff; /* Ensure text color remains white */\n"
"}\n"
"\n"
"/* Active Button (Current Page) */\n"
"QPushButton#activeButton {\n"
"    background-color: #004aad;\n"
"    color: #ffffff; /* Ensure text color remains white */\n"
"}")
        self.pushButton_search.setObjectName("pushButton_search")
        self.comboBox_filterOrders = QtWidgets.QComboBox(self.frame_45)
        self.comboBox_filterOrders.setGeometry(QtCore.QRect(1350, 50, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.comboBox_filterOrders.setFont(font)
        self.comboBox_filterOrders.setStyleSheet("    background-color: #ebe0cc;\n"
"    border-radius: 15px;\n"
"font-size:28px;\n"
"text-align: center;")
        self.comboBox_filterOrders.setObjectName("comboBox_filterOrders")
        self.comboBox_filterOrders.addItem("")
        self.comboBox_filterOrders.addItem("")
        self.comboBox_filterOrders.addItem("")
        self.comboBox_filterOrders.addItem("")
        self.frame_29 = QtWidgets.QFrame(self.frame_45)
        self.frame_29.setGeometry(QtCore.QRect(50, 150, 661, 61))
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.pushButton_order = QtWidgets.QPushButton(self.frame_29)
        self.pushButton_order.setGeometry(QtCore.QRect(0, 10, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        self.pushButton_order.setFont(font)
        self.pushButton_order.setStyleSheet("QPushButton {\n"
"    background-color: #003366; /* Blue color */\n"
"    border-radius: 10px;\n"
"    font-size: 24px;\n"
"    color: #ffffff; /* Corrected from font-color */\n"
"    padding: 9px;\n"
"    font-family: \"Verdana\", sans-serif;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color: #8d2721;\n"
"    color: #ffffff; /* Ensure text color remains white */\n"
"}\n"
"\n"
"/* Active Button (Current Page) */\n"
"QPushButton#activeButton {\n"
"    background-color:#8d2721;\n"
"    color: #ffffff; /* Ensure text color remains white */\n"
"}")
        self.pushButton_order.setObjectName("pushButton_order")
        self.pushButton_orderDetail = QtWidgets.QPushButton(self.frame_29)
        self.pushButton_orderDetail.setGeometry(QtCore.QRect(220, 10, 421, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        self.pushButton_orderDetail.setFont(font)
        self.pushButton_orderDetail.setStyleSheet("QPushButton {\n"
"    background-color: #003366; /* Blue color */\n"
"    border-radius: 10px;\n"
"    font-size: 24px;\n"
"    color: #ffffff; /* Corrected from font-color */\n"
"    padding: 9px;\n"
"    font-family: \"Verdana\", sans-serif;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color: #8d2721;\n"
"    color: #ffffff; /* Ensure text color remains white */\n"
"}\n"
"\n"
"/* Active Button (Current Page) */\n"
"QPushButton#activeButton {\n"
"    background-color: #8d2721;\n"
"    color: #ffffff; /* Ensure text color remains white */\n"
"}")
        self.pushButton_orderDetail.setObjectName("pushButton_orderDetail")

        self.retranslateUi(CASHIER_ORDERS)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CASHIER_ORDERS)

    def retranslateUi(self, CASHIER_ORDERS):
        _translate = QtCore.QCoreApplication.translate
        CASHIER_ORDERS.setWindowTitle(_translate("CASHIER_ORDERS", "Form"))
        self.JJelevate_text.setText(_translate("CASHIER_ORDERS", "J & J ELEVATE"))
        self.pushButton_Dashboard_CASHIER.setText(_translate("CASHIER_ORDERS", " Dashboard   "))
        self.pushButton_Inventory_CASHIER.setText(_translate("CASHIER_ORDERS", "Inventory"))
        self.pushButton_Orders_CASHIER.setText(_translate("CASHIER_ORDERS", " Orders"))
        self.pushButton_Sales_CASHIER.setText(_translate("CASHIER_ORDERS", "  Sales"))
        self.pushButton_Account_CASHIER.setText(_translate("CASHIER_ORDERS", " Account     "))
        self.pushButton_LogOut_CASHIER.setText(_translate("CASHIER_ORDERS", "Log out"))
        self.pushButton_Stock_History_CASHIER.setText(_translate("CASHIER_ORDERS", "Stock History"))
        item = self.tableWidget_order.horizontalHeaderItem(0)
        item.setText(_translate("CASHIER_ORDERS", "Order ID"))
        item = self.tableWidget_order.horizontalHeaderItem(1)
        item.setText(_translate("CASHIER_ORDERS", "Date Created"))
        item = self.tableWidget_order.horizontalHeaderItem(2)
        item.setText(_translate("CASHIER_ORDERS", "Status"))
        item = self.tableWidget_order.horizontalHeaderItem(3)
        item.setText(_translate("CASHIER_ORDERS", "Total Amount (₱)"))
        item = self.tableWidget_order.horizontalHeaderItem(4)
        item.setText(_translate("CASHIER_ORDERS", "Service"))
        item = self.tableWidget_order.horizontalHeaderItem(5)
        item.setText(_translate("CASHIER_ORDERS", "Customer Name"))
        item = self.tableWidget_order.horizontalHeaderItem(6)
        item.setText(_translate("CASHIER_ORDERS", "Contact Number"))
        item = self.tableWidget_order.horizontalHeaderItem(7)
        item.setText(_translate("CASHIER_ORDERS", "Customer Address"))
        item = self.tableWidget_order.horizontalHeaderItem(8)
        item.setText(_translate("CASHIER_ORDERS", "Processed by"))
        self.label.setText(_translate("CASHIER_ORDERS", "CASHIER"))
        item = self.tableWidget_orderDetails.horizontalHeaderItem(0)
        item.setText(_translate("CASHIER_ORDERS", "Order ID"))
        item = self.tableWidget_orderDetails.horizontalHeaderItem(1)
        item.setText(_translate("CASHIER_ORDERS", "Order Detail ID"))
        item = self.tableWidget_orderDetails.horizontalHeaderItem(2)
        item.setText(_translate("CASHIER_ORDERS", "Product"))
        item = self.tableWidget_orderDetails.horizontalHeaderItem(3)
        item.setText(_translate("CASHIER_ORDERS", "Quanity"))
        item = self.tableWidget_orderDetails.horizontalHeaderItem(4)
        item.setText(_translate("CASHIER_ORDERS", "Unit Price"))
        item = self.tableWidget_orderDetails.horizontalHeaderItem(5)
        item.setText(_translate("CASHIER_ORDERS", "Discount"))
        item = self.tableWidget_orderDetails.horizontalHeaderItem(6)
        item.setText(_translate("CASHIER_ORDERS", "Total Amount"))
        item = self.tableWidget_orderDetails.horizontalHeaderItem(7)
        item.setText(_translate("CASHIER_ORDERS", "Date Created"))
        self.lineEdit__QuickSearch_Sales.setPlaceholderText(_translate("CASHIER_ORDERS", " 🔍︎  Quick Search"))
        self.pushButton_search.setText(_translate("CASHIER_ORDERS", "Search"))
        self.comboBox_filterOrders.setCurrentText(_translate("CASHIER_ORDERS", "    Filter Orders"))
        self.comboBox_filterOrders.setItemText(0, _translate("CASHIER_ORDERS", "    Filter Orders"))
        self.comboBox_filterOrders.setItemText(1, _translate("CASHIER_ORDERS", "Daily"))
        self.comboBox_filterOrders.setItemText(2, _translate("CASHIER_ORDERS", "Weekly"))
        self.comboBox_filterOrders.setItemText(3, _translate("CASHIER_ORDERS", "Monthly"))
        self.pushButton_order.setText(_translate("CASHIER_ORDERS", "Orders"))
        self.pushButton_orderDetail.setText(_translate("CASHIER_ORDERS", "View Order Details"))
