# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/raw_files/UI_OOrders.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OWNER_ORDERS(object):
    def setupUi(self, OWNER_ORDERS):
        OWNER_ORDERS.setObjectName("OWNER_ORDERS")
        OWNER_ORDERS.resize(1921, 1005)
        OWNER_ORDERS.setStyleSheet("background: white;")
        self.stackedWidget = QtWidgets.QStackedWidget(OWNER_ORDERS)
        self.stackedWidget.setGeometry(QtCore.QRect(300, 210, 1621, 771))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.tableWidget_order = QtWidgets.QTableWidget(self.page)
        self.tableWidget_order.setGeometry(QtCore.QRect(50, 0, 1531, 741))
        self.tableWidget_order.setStyleSheet("padding: 1;")
        self.tableWidget_order.setObjectName("tableWidget_order")
        self.tableWidget_order.setColumnCount(9)
        self.tableWidget_order.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_order.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_order.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_order.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_order.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_order.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_order.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_order.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_order.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_order.setHorizontalHeaderItem(8, item)
        self.tableWidget_order.horizontalHeader().setDefaultSectionSize(265)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tableWidget_orderDetails = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget_orderDetails.setGeometry(QtCore.QRect(50, 0, 1531, 741))
        self.tableWidget_orderDetails.setStyleSheet("padding: 1;")
        self.tableWidget_orderDetails.setObjectName("tableWidget_orderDetails")
        self.tableWidget_orderDetails.setColumnCount(8)
        self.tableWidget_orderDetails.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_orderDetails.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_orderDetails.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_orderDetails.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_orderDetails.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_orderDetails.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_orderDetails.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_orderDetails.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_orderDetails.setHorizontalHeaderItem(7, item)
        self.tableWidget_orderDetails.horizontalHeader().setDefaultSectionSize(265)
        self.stackedWidget.addWidget(self.page_2)
        self.frame_45 = QtWidgets.QFrame(OWNER_ORDERS)
        self.frame_45.setGeometry(QtCore.QRect(300, 0, 1621, 211))
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.comboBox_filterOrders = QtWidgets.QComboBox(self.frame_45)
        self.comboBox_filterOrders.setGeometry(QtCore.QRect(1350, 50, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.comboBox_filterOrders.setFont(font)
        self.comboBox_filterOrders.setStyleSheet("    background-color: #ebe0cc;\n"
"    border-radius: 15px;\n"
"font-size:28px;\n"
"text-align: center;")
        self.comboBox_filterOrders.setObjectName("comboBox_filterOrders")
        self.comboBox_filterOrders.addItem("")
        self.comboBox_filterOrders.addItem("")
        self.comboBox_filterOrders.addItem("")
        self.comboBox_filterOrders.addItem("")
        self.frame_29 = QtWidgets.QFrame(self.frame_45)
        self.frame_29.setGeometry(QtCore.QRect(50, 150, 661, 61))
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.pushButton_order = QtWidgets.QPushButton(self.frame_29)
        self.pushButton_order.setGeometry(QtCore.QRect(0, 10, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        self.pushButton_order.setFont(font)
        self.pushButton_order.setStyleSheet("QPushButton {\n"
"    background-color: #003366; /* Blue color */\n"
"    border-radius: 10px;\n"
"    font-size: 24px;\n"
"    color: #ffffff; /* Corrected from font-color */\n"
"    padding: 9px;\n"
"    font-family: \"Verdana\", sans-serif;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color: #8d2721;\n"
"    color: #ffffff; /* Ensure text color remains white */\n"
"}\n"
"\n"
"/* Active Button (Current Page) */\n"
"QPushButton#activeButton {\n"
"    background-color:#8d2721;\n"
"    color: #ffffff; /* Ensure text color remains white */\n"
"}")
        self.pushButton_order.setObjectName("pushButton_order")
        self.pushButton_orderDetail = QtWidgets.QPushButton(self.frame_29)
        self.pushButton_orderDetail.setGeometry(QtCore.QRect(220, 10, 421, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        self.pushButton_orderDetail.setFont(font)
        self.pushButton_orderDetail.setStyleSheet("QPushButton {\n"
"    background-color: #003366; /* Blue color */\n"
"    border-radius: 10px;\n"
"    font-size: 24px;\n"
"    color: #ffffff; /* Corrected from font-color */\n"
"    padding: 9px;\n"
"    font-family: \"Verdana\", sans-serif;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color: #8d2721;\n"
"    color: #ffffff; /* Ensure text color remains white */\n"
"}\n"
"\n"
"/* Active Button (Current Page) */\n"
"QPushButton#activeButton {\n"
"    background-color: #8d2721;\n"
"    color: #ffffff; /* Ensure text color remains white */\n"
"}")
        self.pushButton_orderDetail.setObjectName("pushButton_orderDetail")
        self.frame_4 = QtWidgets.QFrame(self.frame_45)
        self.frame_4.setGeometry(QtCore.QRect(830, 50, 511, 71))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.lineEdit__QuickSearch_Orders = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit__QuickSearch_Orders.setGeometry(QtCore.QRect(10, 10, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit__QuickSearch_Orders.setFont(font)
        self.lineEdit__QuickSearch_Orders.setStyleSheet("\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    padding: 2px;\n"
"    text-align: center;\n"
"\n"
"\n"
"\n"
"")
        self.lineEdit__QuickSearch_Orders.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit__QuickSearch_Orders.setClearButtonEnabled(False)
        self.lineEdit__QuickSearch_Orders.setObjectName("lineEdit__QuickSearch_Orders")
        self.label_18 = QtWidgets.QLabel(self.frame_4)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 71, 51))
        self.label_18.setStyleSheet("background: transparent;\n"
"padding: 5;\n"
"")
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("ui/raw_files\\../resources/images/search.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.pushButton_searchOrders = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_searchOrders.setGeometry(QtCore.QRect(300, 10, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_searchOrders.setFont(font)
        self.pushButton_searchOrders.setStyleSheet("    QPushButton {\n"
"        background-color: #003366;\n"
"        color: white;\n"
"        padding: 2px;\n"
"        text-align: center;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgba(0, 51, 102, 0.9);\n"
"    }")
        self.pushButton_searchOrders.setObjectName("pushButton_searchOrders")
        self.orderReportText = QtWidgets.QLabel(self.frame_45)
        self.orderReportText.setGeometry(QtCore.QRect(50, 50, 501, 71))
        self.orderReportText.setStyleSheet("color: #12245c;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"background: transparent;\n"
"font-size: 50px;")
        self.orderReportText.setObjectName("orderReportText")
        self.LeftMenuBar = QtWidgets.QFrame(OWNER_ORDERS)
        self.LeftMenuBar.setGeometry(QtCore.QRect(0, 0, 301, 1011))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LeftMenuBar.setFont(font)
        self.LeftMenuBar.setStyleSheet("background-color: rgba(235, 224, 204, 0.47); /* #ebe0cc with 47% opacity */")
        self.LeftMenuBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LeftMenuBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LeftMenuBar.setObjectName("LeftMenuBar")
        self.JJelevate_text_2 = QtWidgets.QLabel(self.LeftMenuBar)
        self.JJelevate_text_2.setGeometry(QtCore.QRect(60, 220, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.JJelevate_text_2.setFont(font)
        self.JJelevate_text_2.setStyleSheet("color: #12245c;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"background: transparent;\n"
"font-size: 30px;")
        self.JJelevate_text_2.setScaledContents(True)
        self.JJelevate_text_2.setObjectName("JJelevate_text_2")
        self.Logo = QtWidgets.QLabel(self.LeftMenuBar)
        self.Logo.setGeometry(QtCore.QRect(30, 50, 241, 171))
        self.Logo.setStyleSheet("background: transparent;")
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("ui/raw_files\\../resources/images/JJLOGO.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setAlignment(QtCore.Qt.AlignCenter)
        self.Logo.setObjectName("Logo")
        self.pushButton_Dashboard = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Dashboard.setGeometry(QtCore.QRect(30, 310, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_Dashboard.setFont(font)
        self.pushButton_Dashboard.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/raw_files\\../resources/images/dashboard_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Dashboard.setIcon(icon)
        self.pushButton_Dashboard.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Dashboard.setObjectName("pushButton_Dashboard")
        self.pushButton_Inventory = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Inventory.setGeometry(QtCore.QRect(30, 390, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Inventory.setFont(font)
        self.pushButton_Inventory.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui/raw_files\\../resources/images/inventory_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Inventory.setIcon(icon1)
        self.pushButton_Inventory.setIconSize(QtCore.QSize(50, 45))
        self.pushButton_Inventory.setObjectName("pushButton_Inventory")
        self.pushButton_Orders = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Orders.setGeometry(QtCore.QRect(30, 470, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Orders.setFont(font)
        self.pushButton_Orders.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui/raw_files\\../resources/images/orders_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Orders.setIcon(icon2)
        self.pushButton_Orders.setIconSize(QtCore.QSize(46, 42))
        self.pushButton_Orders.setObjectName("pushButton_Orders")
        self.pushButton_Sales = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Sales.setGeometry(QtCore.QRect(30, 550, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Sales.setFont(font)
        self.pushButton_Sales.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ui/raw_files\\../resources/images/sales_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Sales.setIcon(icon3)
        self.pushButton_Sales.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_Sales.setObjectName("pushButton_Sales")
        self.pushButton_Account = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Account.setGeometry(QtCore.QRect(30, 710, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Account.setFont(font)
        self.pushButton_Account.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ui/raw_files\\../resources/images/account_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Account.setIcon(icon4)
        self.pushButton_Account.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_Account.setObjectName("pushButton_Account")
        self.pushButton_LogOut = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_LogOut.setGeometry(QtCore.QRect(30, 890, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(87)
        self.pushButton_LogOut.setFont(font)
        self.pushButton_LogOut.setStyleSheet("QPushButton {\n"
"    background-color:#022162;\n"
"color:white;\n"
"font-weight: 700;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"font-size: 14;\n"
"text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"        background-color: rgba(2, 33, 98, 0.8);\n"
"        color: white;\n"
"    font-weight: 700;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ui/raw_files\\../resources/images/WHITElogout_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_LogOut.setIcon(icon5)
        self.pushButton_LogOut.setIconSize(QtCore.QSize(38, 38))
        self.pushButton_LogOut.setObjectName("pushButton_LogOut")
        self.pushButton_Stock_History = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Stock_History.setGeometry(QtCore.QRect(30, 630, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Stock_History.setFont(font)
        self.pushButton_Stock_History.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        self.pushButton_Stock_History.setIcon(icon1)
        self.pushButton_Stock_History.setIconSize(QtCore.QSize(50, 45))
        self.pushButton_Stock_History.setObjectName("pushButton_Stock_History")
        self.JJelevate_text_3 = QtWidgets.QLabel(self.LeftMenuBar)
        self.JJelevate_text_3.setGeometry(QtCore.QRect(130, 220, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.JJelevate_text_3.setFont(font)
        self.JJelevate_text_3.setStyleSheet("color: #d75413;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"background: transparent;\n"
"font-size: 29px;\n"
"")
        self.JJelevate_text_3.setScaledContents(True)
        self.JJelevate_text_3.setObjectName("JJelevate_text_3")

        self.retranslateUi(OWNER_ORDERS)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(OWNER_ORDERS)

    def retranslateUi(self, OWNER_ORDERS):
        _translate = QtCore.QCoreApplication.translate
        OWNER_ORDERS.setWindowTitle(_translate("OWNER_ORDERS", "Form"))
        item = self.tableWidget_order.horizontalHeaderItem(0)
        item.setText(_translate("OWNER_ORDERS", "Order ID"))
        item = self.tableWidget_order.horizontalHeaderItem(1)
        item.setText(_translate("OWNER_ORDERS", "Date Created"))
        item = self.tableWidget_order.horizontalHeaderItem(2)
        item.setText(_translate("OWNER_ORDERS", "Status"))
        item = self.tableWidget_order.horizontalHeaderItem(3)
        item.setText(_translate("OWNER_ORDERS", "Total Amount (₱)"))
        item = self.tableWidget_order.horizontalHeaderItem(4)
        item.setText(_translate("OWNER_ORDERS", "Service"))
        item = self.tableWidget_order.horizontalHeaderItem(5)
        item.setText(_translate("OWNER_ORDERS", "Customer Name"))
        item = self.tableWidget_order.horizontalHeaderItem(6)
        item.setText(_translate("OWNER_ORDERS", "Contact Number"))
        item = self.tableWidget_order.horizontalHeaderItem(7)
        item.setText(_translate("OWNER_ORDERS", "Customer Address"))
        item = self.tableWidget_order.horizontalHeaderItem(8)
        item.setText(_translate("OWNER_ORDERS", "Processed by"))
        item = self.tableWidget_orderDetails.horizontalHeaderItem(0)
        item.setText(_translate("OWNER_ORDERS", "Order ID"))
        item = self.tableWidget_orderDetails.horizontalHeaderItem(1)
        item.setText(_translate("OWNER_ORDERS", "Order Detail ID"))
        item = self.tableWidget_orderDetails.horizontalHeaderItem(2)
        item.setText(_translate("OWNER_ORDERS", "Product"))
        item = self.tableWidget_orderDetails.horizontalHeaderItem(3)
        item.setText(_translate("OWNER_ORDERS", "Quantity"))
        item = self.tableWidget_orderDetails.horizontalHeaderItem(4)
        item.setText(_translate("OWNER_ORDERS", "Unit Price"))
        item = self.tableWidget_orderDetails.horizontalHeaderItem(5)
        item.setText(_translate("OWNER_ORDERS", "Discount"))
        item = self.tableWidget_orderDetails.horizontalHeaderItem(6)
        item.setText(_translate("OWNER_ORDERS", "Total Amount"))
        item = self.tableWidget_orderDetails.horizontalHeaderItem(7)
        item.setText(_translate("OWNER_ORDERS", "Date Created"))
        self.comboBox_filterOrders.setCurrentText(_translate("OWNER_ORDERS", "    Filter Orders"))
        self.comboBox_filterOrders.setItemText(0, _translate("OWNER_ORDERS", "    Filter Orders"))
        self.comboBox_filterOrders.setItemText(1, _translate("OWNER_ORDERS", "Daily"))
        self.comboBox_filterOrders.setItemText(2, _translate("OWNER_ORDERS", "Weekly"))
        self.comboBox_filterOrders.setItemText(3, _translate("OWNER_ORDERS", "Monthly"))
        self.pushButton_order.setText(_translate("OWNER_ORDERS", "Orders"))
        self.pushButton_orderDetail.setText(_translate("OWNER_ORDERS", "View Order Details"))
        self.lineEdit__QuickSearch_Orders.setPlaceholderText(_translate("OWNER_ORDERS", "      Quick Search"))
        self.pushButton_searchOrders.setText(_translate("OWNER_ORDERS", "Search"))
        self.orderReportText.setText(_translate("OWNER_ORDERS", "Order Report"))
        self.JJelevate_text_2.setText(_translate("OWNER_ORDERS", "J&J "))
        self.pushButton_Dashboard.setText(_translate("OWNER_ORDERS", "  Home   "))
        self.pushButton_Inventory.setText(_translate("OWNER_ORDERS", "Inventory"))
        self.pushButton_Orders.setText(_translate("OWNER_ORDERS", " Orders"))
        self.pushButton_Sales.setText(_translate("OWNER_ORDERS", "  Sales"))
        self.pushButton_Account.setText(_translate("OWNER_ORDERS", " Account     "))
        self.pushButton_LogOut.setText(_translate("OWNER_ORDERS", "   Log out"))
        self.pushButton_Stock_History.setText(_translate("OWNER_ORDERS", "Stock History"))
        self.JJelevate_text_3.setText(_translate("OWNER_ORDERS", "Elevate"))
